import LocalizedStrings from "react-localization";

export const strings = new LocalizedStrings({
  en: {
    topTen: "Top 10",
    screener: "Screener",
    navLinkArgaam: "Argaam",
    navLinkAbout: "About Us",
    sector: "Sector",
    date: "Last Update :",
    code: "Symbol",
    companies: "Companies",
    sector: "Sector",
    pemtt: "P/E (MTT)",
    par: "PE/(AR)",
    bookValue: "Book Value (Last Fiscal Period)",
    priceBook: "Price/Book",
    priceSales: "Price/Sales",
    stockScreener: "Stock Screener",
    topTenCompanies: "Top Ten Companies",
    grossProfitMargins: "Gross Profit Margins",
    netMargin: "Net Margin",
    returnOnAssets: "Return On assets",
    returnOnEquity: "Return On equity",
    netIndebt: "Net indebtedness/quity",
    evRevenues: "EV / Revenues",
    ttm: "TTM",
    marketCap: "Market Cap (LFY)",
    capital: "Capital ( LFY )",
    assets: "Assets ( LFY )",
    shareholder: "Shareholder's Equity (LFY)",
    revenue: "Revenue (TTM)",
    profit: "Profit (TTM)",
    rank: "Rank",
    charts: "Charts",
    neg: "NEG",
    moreThan100: "More than 100",
    pe: "P/E",
    prev: "Previous",
    next: "Next",
    notFound: "No results found",
    title: "Argaam Screener",
    errorPage: "Something went wrong...",
    reset: "Reset",
    exportCurrent: "Export Current Tab",
    exportAllTabs: "Export All Tabs",
    finRatioMsg: "Some Ratios are not applicable",
    banks: "Banks",
    insurance: "Insurance",
    reits: "Reits",
    financing: "Financing",
    and: "and",
  },
  ar: {
    topTen: "أعلى 10",
    screener: "تحليل الاسهم",
    navLinkArgaam: "أرقام",
    navLinkAbout: "معلومات عنا",
    code: "الرمز",
    companies: "الشركة",
    sector: "القطاع",
    pemtt: "مكرر الربح ( أخر 12 )",
    par: "(معدل سنوياً) مكرر الربح",
    priceBook: "(اخر فترة مالية) القيمة الدفترية",
    priceSales: "(اخر 12) مضاعف الإيرادات",
    date: "آخر تحديث :",
    bookValue: "(معدل سنوياً) مكرر الربح",
    stockScreener: "نتيجة الفلتر",
    topTenCompanies: "أعلى 10 شركات",
    grossProfitMargins: "هامش الربح الإجمالي",
    netMargin: "هامش الربح الصافي",
    returnOnAssets: "% العائد على الأصول",
    returnOnEquity: "% العائد على حقوق المساهمين",
    netIndebt: "صافي المديونية/ حقوق المساهمين",
    evRevenues: "المنشآة/ الايرادات",
    ttm: "( اخر 12 )",
    marketCap: "( اخر اغلاق ) القيمة السوقية",
    capital: "( اخر فترة مالية ) رآس المال",
    assets: "(اخر فترة مالية) الأصول",
    shareholder: "(اخر فترة مالية) حقوق المساهمين",
    revenue: "(اخر 12) الايردات",
    profit: "(اخر 12) الأرباح",
    rank: "الترتيب",
    charts: "الرسوم البيانية",
    neg: "سالب",
    moreThan100: "أكبر من 100",
    pe: "مكرر الربح",
    prev: "السابق",
    next: "التالي",
    notFound: "لا توجد نتائج للبحث",
    title: "تحليل الأسهم",
    errorPage: "حدث خطأ ما...",
    reset: "إعادة تعيين",
    exportCurrent: "تصدير علامة التبويب الحالية",
    exportAllTabs: "تصدير كافة علامات التبويب",
    finRatioMsg: "بعض المؤشرات لا تنطبق على",
    banks: "البنوك",
    insurance: "التأمين",
    reits: "الريت",
    financing: "التمويل",
    and: "و",
  },
});

export const SECTORS = {
  BANKING: 8,
  INSURANCE: 15,
  REITS: 238,
  FINANCING: 240,
};

export const LANGUAGES = {
  EN: "en",
  AR: "ar",
};

export const LANGUAGEID = {
  AR: 1,
  EN: 2,
};

export const PAGES = {
  SCREENER: 1,
  TOPTEN: 2,
};

export const SECTIONS = {
  STOCK_SCREENER: 3,
  TOPTEN_COMPANIES: 4,
};

export const TABS = {
  S_PE: 5,
  S_FINANCIAL_RATIO: 6,
  S_PERFORMANCE_AND_SIZE: 7,
  S_GROWTH: 13,

  T_RANKING: 8,
  T_STOCK_PERFORMANCE: 9,
  T_ARR_MULTIPLE: 10,
  T_FINANCIAL_RATIO: 11,
  T_GROWTH_AND_DIVIDENDS: 12,
};

export const INDICATOR = {
  AVERAGE: 1,
  TOTAL: 2,
};
