export const countryCodes = [
  { CountryNameAr: "الجزائر", CountryNameEn: "Algeria", CountryCode: "+213" },
  { CountryNameAr: "أندورا", CountryNameEn: "Andorra", CountryCode: "+376" },
  { CountryNameAr: "أنغولا", CountryNameEn: "Angola", CountryCode: "+244" },
  { CountryNameAr: "أنغويلا", CountryNameEn: "Anguilla", CountryCode: "+264" },
  {
    CountryNameAr: "الأرجنتين",
    CountryNameEn: "Argentina",
    CountryCode: "+54",
  },
  { CountryNameAr: "أستراليا", CountryNameEn: "Australia", CountryCode: "+61" },
  { CountryNameAr: "النمسا", CountryNameEn: "Austria", CountryCode: "+43" },
  { CountryNameAr: "البهاما", CountryNameEn: "Bahamas", CountryCode: "+1242" },
  { CountryNameAr: "البحرين", CountryNameEn: "Bahrain", CountryCode: "+973" },
  {
    CountryNameAr: "بنغلاديش",
    CountryNameEn: "Bangladesh",
    CountryCode: "+880",
  },
  { CountryNameAr: "باربادوس", CountryNameEn: "Barbados", CountryCode: "+246" },
  { CountryNameAr: "بلجيكا", CountryNameEn: "Belgium", CountryCode: "+32" },
  { CountryNameAr: "بليز", CountryNameEn: "Belize", CountryCode: "+501" },
  { CountryNameAr: "بنين", CountryNameEn: "Benin", CountryCode: "+229" },
  { CountryNameAr: "جزر برمود", CountryNameEn: "Bermuda", CountryCode: "+441" },
  { CountryNameAr: "بوتان", CountryNameEn: "Bhutan", CountryCode: "+975" },
  { CountryNameAr: "بوليفيا", CountryNameEn: "Bolivia", CountryCode: "+591" },
  {
    CountryNameAr: "البوسنة و الهرسك",
    CountryNameEn: "Bosina & Herzegovina",
    CountryCode: "+387",
  },
  { CountryNameAr: "بوتسوانا", CountryNameEn: "Botswana", CountryCode: "+267" },
  { CountryNameAr: "البرازيل", CountryNameEn: "Brazil", CountryCode: "+55" },
  { CountryNameAr: "بلغاريا", CountryNameEn: "Bulgaria", CountryCode: "+359" },
  { CountryNameAr: "كندا", CountryNameEn: "Canada", CountryCode: "+1" },
  { CountryNameAr: "تشيلي", CountryNameEn: "Chile", CountryCode: "+56" },
  { CountryNameAr: "الصين", CountryNameEn: "China", CountryCode: "+86" },
  {
    CountryNameAr: "كوستاريكا",
    CountryNameEn: "Costa Rica",
    CountryCode: "+506",
  },
  { CountryNameAr: "كوبا", CountryNameEn: "Cuba", CountryCode: "+53" },
  { CountryNameAr: "قبرص", CountryNameEn: "Cyprus", CountryCode: "+357" },
  { CountryNameAr: "التشيك", CountryNameEn: "Czech", CountryCode: "+420" },
  { CountryNameAr: "الدنمارك", CountryNameEn: "Denmark", CountryCode: "+45" },
  { CountryNameAr: "الإكوادور", CountryNameEn: "Ecuador", CountryCode: "+593" },
  { CountryNameAr: "مصر", CountryNameEn: "Egypt", CountryCode: "+20" },
  { CountryNameAr: "إريتريا", CountryNameEn: "Eritrea", CountryCode: "+291" },
  { CountryNameAr: "إثيوبيا", CountryNameEn: "Ethiopia", CountryCode: "+251" },
  {
    CountryNameAr: "جزر فوكلاند",
    CountryNameEn: "Falkland Islands",
    CountryCode: "+500",
  },
  {
    CountryNameAr: "جزر فارو",
    CountryNameEn: "Faroe Island",
    CountryCode: "+298",
  },
  { CountryNameAr: "فيجي", CountryNameEn: "Fiji", CountryCode: "+679" },
  { CountryNameAr: "فنلندا", CountryNameEn: "Finland", CountryCode: "+358" },
  { CountryNameAr: "فرنسا", CountryNameEn: "France", CountryCode: "+33" },
  {
    CountryNameAr: "غويانا الفرنسية",
    CountryNameEn: "French Guyana",
    CountryCode: "+594",
  },
  {
    CountryNameAr: "بولينيزيا الفرنسية",
    CountryNameEn: "French Polynesia",
    CountryCode: "+689",
  },
  { CountryNameAr: "الغابون", CountryNameEn: "Gabon", CountryCode: "+241" },
  { CountryNameAr: "غامبيا", CountryNameEn: "Gambia", CountryCode: "+220" },
  { CountryNameAr: "جيورجيا", CountryNameEn: "Georgia", CountryCode: "+995" },
  { CountryNameAr: "ألمانيا", CountryNameEn: "Germany", CountryCode: "+49" },
  { CountryNameAr: "غانا", CountryNameEn: "Ghana", CountryCode: "+233" },
  {
    CountryNameAr: "جبل طارق",
    CountryNameEn: "Gibralter",
    CountryCode: "+350",
  },
  { CountryNameAr: "اليونان", CountryNameEn: "Greece", CountryCode: "+30" },
  {
    CountryNameAr: "جرينلاند",
    CountryNameEn: "Greenland",
    CountryCode: "+299",
  },
  {
    CountryNameAr: "جزر جوادلوب",
    CountryNameEn: "Guadeloupe",
    CountryCode: "+590",
  },
  { CountryNameAr: "جوام", CountryNameEn: "Guam", CountryCode: "+1671" },
  {
    CountryNameAr: "غواتيمال",
    CountryNameEn: "Guatemala",
    CountryCode: "+502",
  },
  { CountryNameAr: "غيانا", CountryNameEn: "Guinea", CountryCode: "+224" },
  { CountryNameAr: "غيانا", CountryNameEn: "Guyana Rep.", CountryCode: "+592" },
  { CountryNameAr: "هايتي", CountryNameEn: "Haiti Rep.", CountryCode: "+509" },
  {
    CountryNameAr: "هندوراس",
    CountryNameEn: "Honduras Rep.",
    CountryCode: "+504",
  },
  {
    CountryNameAr: "هونغ كونغ",
    CountryNameEn: "Hong Kong",
    CountryCode: "+852",
  },
  { CountryNameAr: "المجر", CountryNameEn: "Hungary", CountryCode: "+36" },
  { CountryNameAr: "آيسلندا", CountryNameEn: "Iceland", CountryCode: "+354" },
  { CountryNameAr: "الهند", CountryNameEn: "India", CountryCode: "+91" },
  { CountryNameAr: "ايران", CountryNameEn: "Iran", CountryCode: "+98" },
  { CountryNameAr: "العراق", CountryNameEn: "Iraq", CountryCode: "+964" },
  { CountryNameAr: "أيرلندا", CountryNameEn: "Ireland", CountryCode: "+353" },
  { CountryNameAr: "إسرائيل", CountryNameEn: "Isreal", CountryCode: "+972" },
  { CountryNameAr: "إيطاليا", CountryNameEn: "Italy", CountryCode: "+39" },
  { CountryNameAr: "جمايكا", CountryNameEn: "Jamaica", CountryCode: "+876" },
  { CountryNameAr: "اليابان", CountryNameEn: "Japan", CountryCode: "+81" },
  { CountryNameAr: "الاردن", CountryNameEn: "Jordan", CountryCode: "+962" },
  { CountryNameAr: "كينيا", CountryNameEn: "Kenya", CountryCode: "+254" },
  { CountryNameAr: "كيريباتي", CountryNameEn: "Kiribati", CountryCode: "+686" },
  {
    CountryNameAr: "كوريا الشمالية",
    CountryNameEn: "North Korea",
    CountryCode: "+82",
  },
  { CountryNameAr: "الكويت", CountryNameEn: "Kuwait", CountryCode: "+965" },
  { CountryNameAr: "لاتفيا", CountryNameEn: "Latvia", CountryCode: "+371" },
  { CountryNameAr: "لبنان", CountryNameEn: "Lebanon", CountryCode: "+961" },
  {
    CountryNameAr: "ليبيريا",
    CountryNameEn: "Liberia Rep.",
    CountryCode: "+231",
  },
  { CountryNameAr: "ليبيا", CountryNameEn: "Libya", CountryCode: "+218" },
  {
    CountryNameAr: "ليختنشتين",
    CountryNameEn: "Liechtenstein",
    CountryCode: "+423",
  },
  { CountryNameAr: "لتوانيا", CountryNameEn: "Lithuania", CountryCode: "+370" },
  {
    CountryNameAr: "لوكسمبورغ",
    CountryNameEn: "Luxembourg",
    CountryCode: "+352",
  },
  { CountryNameAr: "ماكاو", CountryNameEn: "Macao", CountryCode: "+853" },
  { CountryNameAr: "مدغشقر", CountryNameEn: "Madagascar", CountryCode: "+261" },
  { CountryNameAr: "مالاوي", CountryNameEn: "Malawi", CountryCode: "+265" },
  { CountryNameAr: "ماليزيا", CountryNameEn: "Malaysia", CountryCode: "+60" },
  {
    CountryNameAr: "جزر المالديف",
    CountryNameEn: "Maldives",
    CountryCode: "+960",
  },
  { CountryNameAr: "مالي", CountryNameEn: "Mali Rep.", CountryCode: "+223" },
  { CountryNameAr: "مالطا", CountryNameEn: "Malta", CountryCode: "+356" },
  {
    CountryNameAr: "موريشيوس",
    CountryNameEn: "Mauritius",
    CountryCode: "+230",
  },
  { CountryNameAr: "مايوت", CountryNameEn: "Mayotee", CountryCode: "+262" },
  { CountryNameAr: "المكسيك", CountryNameEn: "Mexico", CountryCode: "+52" },
  {
    CountryNameAr: "منغوليا",
    CountryNameEn: "Mongolia Rep.",
    CountryCode: "+976",
  },
  { CountryNameAr: "المغرب", CountryNameEn: "Morocco", CountryCode: "+212" },
  {
    CountryNameAr: "موزمبيق",
    CountryNameEn: "Mozambique",
    CountryCode: "+258",
  },
  { CountryNameAr: "بورما", CountryNameEn: "Myanmar", CountryCode: "+95" },
  { CountryNameAr: "ناميبيا", CountryNameEn: "Namibia", CountryCode: "+264" },
  { CountryNameAr: "ناورو", CountryNameEn: "Nauru Rep.", CountryCode: "+674" },
  { CountryNameAr: "نيبال", CountryNameEn: "Nepal", CountryCode: "+977" },
  { CountryNameAr: "هولندا", CountryNameEn: "Netherlands", CountryCode: "+31" },
  {
    CountryNameAr: "نيوزيلندا",
    CountryNameEn: "New Zealand",
    CountryCode: "+64",
  },
  {
    CountryNameAr: "نيكاراجوا",
    CountryNameEn: "Nicaragua",
    CountryCode: "+505",
  },
  { CountryNameAr: "النيجر", CountryNameEn: "Niger Rep.", CountryCode: "+227" },
  {
    CountryNameAr: "نيجيريا",
    CountryNameEn: "Nigeria Rep.",
    CountryCode: "+234",
  },
  {
    CountryNameAr: "جزيرة نورفولك",
    CountryNameEn: "Norfolk Island",
    CountryCode: "+672",
  },
  { CountryNameAr: "النرويج", CountryNameEn: "Norway", CountryCode: "+47" },
  { CountryNameAr: "سلطنة عمان", CountryNameEn: "Oman", CountryCode: "+968" },
  { CountryNameAr: "باكستان", CountryNameEn: "Pakistan", CountryCode: "+92" },
  { CountryNameAr: "بالاو", CountryNameEn: "Palau", CountryCode: "+680" },
  { CountryNameAr: "بنما", CountryNameEn: "Panama", CountryCode: "+507" },
  { CountryNameAr: "باراغواي", CountryNameEn: "Paraguay", CountryCode: "+595" },
  { CountryNameAr: "بيرو", CountryNameEn: "Peru", CountryCode: "+51" },
  {
    CountryNameAr: "الفلبين",
    CountryNameEn: "Phillipines",
    CountryCode: "+63",
  },
  { CountryNameAr: "بولندا", CountryNameEn: "Poland", CountryCode: "+48" },
  { CountryNameAr: "البرتغال", CountryNameEn: "Portugal", CountryCode: "+351" },
  { CountryNameAr: "قطر", CountryNameEn: "Qatar", CountryCode: "+974" },
  { CountryNameAr: "رومانيا", CountryNameEn: "Romania", CountryCode: "+40" },
  { CountryNameAr: "روسيا", CountryNameEn: "Russia", CountryCode: "+7" },
  {
    CountryNameAr: "رواندا",
    CountryNameEn: "Rwanda Rep.",
    CountryCode: "+250",
  },
  {
    CountryNameAr: "المملكة العربية السعودية",
    CountryNameEn: "Saudi Arabia",
    CountryCode: "+966",
  },
  { CountryNameAr: "السنغال", CountryNameEn: "Senegal", CountryCode: "+221" },
  { CountryNameAr: "سيشيل", CountryNameEn: "Seychelles", CountryCode: "+248" },
  { CountryNameAr: "سنغافورة", CountryNameEn: "Singapore", CountryCode: "+65" },
  {
    CountryNameAr: "سلوفاكيا",
    CountryNameEn: "Slovak Rep.",
    CountryCode: "+421",
  },
  { CountryNameAr: "سلوفينيا", CountryNameEn: "Slovenia", CountryCode: "+386" },
  {
    CountryNameAr: "جزر سليمان",
    CountryNameEn: "Solomon Island",
    CountryCode: "+677",
  },
  { CountryNameAr: "الصومال", CountryNameEn: "Somalia", CountryCode: "+252" },
  {
    CountryNameAr: "جنوب أفريقيا",
    CountryNameEn: "South Africa",
    CountryCode: "+27",
  },
  { CountryNameAr: "إسبانيا", CountryNameEn: "Spain", CountryCode: "+34" },
  {
    CountryNameAr: "سيريلانكا",
    CountryNameEn: "Sri Lanka",
    CountryCode: "+94",
  },
  { CountryNameAr: "السودان", CountryNameEn: "Sudan", CountryCode: "+249" },
  { CountryNameAr: "السويد", CountryNameEn: "Sweden", CountryCode: "+46" },
  { CountryNameAr: "سويسرا", CountryNameEn: "Switzerland", CountryCode: "+41" },
  { CountryNameAr: "سوريا", CountryNameEn: "Syria", CountryCode: "+963" },
  { CountryNameAr: "تايوان", CountryNameEn: "Taiwan", CountryCode: "+886" },
  { CountryNameAr: "تونس", CountryNameEn: "Tanzania", CountryCode: "+255" },
  { CountryNameAr: "تايلندا", CountryNameEn: "Thailand", CountryCode: "+66" },
  { CountryNameAr: "تركيا", CountryNameEn: "Turkey", CountryCode: "+90" },
  { CountryNameAr: "الإمارات", CountryNameEn: "UAE", CountryCode: "+971" },
  { CountryNameAr: "أوغندا", CountryNameEn: "Uganda", CountryCode: "+256" },
  { CountryNameAr: "أوكرانيا", CountryNameEn: "Ukraine", CountryCode: "+380" },
  { CountryNameAr: "أورغواي", CountryNameEn: "Uruguay", CountryCode: "+598" },
  {
    CountryNameAr: "أوزباكستان",
    CountryNameEn: "Uzbekistan",
    CountryCode: "+998",
  },
  {
    CountryNameAr: "دولة مدينة الفاتيكان",
    CountryNameEn: "Vatican City",
    CountryCode: "+39",
  },
  { CountryNameAr: "فنزويلا", CountryNameEn: "Venezuela", CountryCode: "+58" },
  { CountryNameAr: "فيتنام", CountryNameEn: "Vietnam", CountryCode: "+84" },
  {
    CountryNameAr: "جنوب اليمن",
    CountryNameEn: "Yemen (PDR)",
    CountryCode: "+967",
  },
  {
    CountryNameAr: "اليمن",
    CountryNameEn: "Yemen Arab Republic",
    CountryCode: "+967",
  },
  { CountryNameAr: "زامبيا", CountryNameEn: "Zambia", CountryCode: "+260" },
  { CountryNameAr: "زمبابوي", CountryNameEn: "Zimbabwe", CountryCode: "+263" },
  { CountryNameAr: "فلسطين", CountryNameEn: "Palestine", CountryCode: "+970" },
  {
    CountryNameAr: "جزر الكايمن",
    CountryNameEn: "Cayman Islands",
    CountryCode: "+345",
  },
  {
    CountryNameAr: "المملكة المتحدة",
    CountryNameEn: "United Kingdom",
    CountryCode: "+44",
  },
  {
    CountryNameAr: "كازاخستان",
    CountryNameEn: "Kazakhstan",
    CountryCode: "+7",
  },
  {
    CountryNameAr: "تركمانستان",
    CountryNameEn: "Turkmenistan",
    CountryCode: "+993",
  },
  { CountryNameAr: "تونس", CountryNameEn: "Tunisia", CountryCode: "+216" },
  {
    CountryNameAr: "جزر المارشال",
    CountryNameEn: "Marshall Islands",
    CountryCode: "+692",
  },
  { CountryNameAr: "جيرسي", CountryNameEn: "Jersey", CountryCode: "+44" },
  { CountryNameAr: "أرمينيا", CountryNameEn: "Armenia", CountryCode: "355" },
  { CountryNameAr: "كولومبيا", CountryNameEn: "Colombia", CountryCode: "+57" },
];
