name: CI/CD Workflow

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: [self-hosted, windows]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Build the application
        run: npm run build

      - name: Copy files to local destination
        shell: pwsh
        run: |
          $destinationPath = "C:\inetpub\wwwroot\argaam100\dist"

          # Check if destination directory exists
          if (-Not (Test-Path -Path $destinationPath)) {
            Write-Host "Destination directory does not exist, creating..."
            New-Item -ItemType Directory -Path $destinationPath
          }

          # Copy the build contents to the destination directory
          Copy-Item -Path "dist\*" -Destination $destinationPath -Recurse -Force
          Write-Host "Files copied to $destinationPath"
