name: Deploy to Heroku

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh
          echo "Heroku CLI installed"

      - name: Log in to Heroku Container Registry
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          echo $HEROKU_API_KEY | heroku auth:token

      # Build the Docker image locally (using your Dockerfile)
      - name: Build Docker Image
        run: docker build -t registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web .

      # Push the Docker image to Heroku Container Registry
      - name: Push Docker Image
        run: docker push registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web

      # Release the Docker container on Heroku
      - name: Release the Image on Heroku
        run: heroku container:release web --app ${{ secrets.HEROKU_APP_NAME }}
